name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=20.3.3
  - pandas-profiling=3.2.0
  - pyarrow=13.0.0
  - pydantic=1.10.12
  - pip:
      - wandb==0.12.17
      - ydata_profiling==4.5.1