name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=2.2.2
  - ipython=8.12.2
  - notebook=7.0.4
  - jupyterlab=4.0.6
  - cookiecutter=2.3.1
  - hydra-core=1.3.2
  - matplotlib=3.7.3
  - pandas=2.0.3
  - git=2.42.0
  - pip=20.3.3
  - pip:
      - wandb==0.12.17
